name: Orbisusb672

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        # Checkout the repository
      - uses: actions/checkout@v2
        # Install required stuff needed to build Mira
      - name: preinstall
        run: sudo apt install build-essential git clang lldb clang-tidy clang-tools cppcheck
        # Handle loaderusb crap
      - name: create loaderusb directories
        run: cd loaderusb; make create
      - name: clean loaderusb
        run: cd loaderusb; make clean
      - name: create mira directories
        run: cd kernel; make create
      - name: clean mira
        run: cd kernel; make clean
        # 6.72 Support
      - name: make 6.72 loader
        run: cd loaderusb; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_672 MIRA_CHECKS=TRUE make
      - name: make 6.72 elf
        run: cd kernel; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_672 MIRA_CHECKS=TRUE make
      - name: Upload 6.72 loaderusb
        uses: actions/upload-artifact@v2
        with:
          name: MiraLoader_Orbis_MIRA_PLATFORM_ORBIS_BSD_672.bin
          path: loaderusb/build/MiraLoader_Orbis_MIRA_PLATFORM_ORBIS_BSD_672.bin
      - name: Upload 6.72 elf
        uses: actions/upload-artifact@v2
        with:
          name: Mira_Orbis_MIRA_PLATFORM_ORBIS_BSD_672.elf
          path: kernel/build/Mira_Orbis_MIRA_PLATFORM_ORBIS_BSD_672.elf